### ISSUE TITLE
Beta looks odd at medium widths

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-html-tools#413] opened 2021-06-05 12:26 UTC
At medium browser widths, the alternative modes are mostly out of bounds.

![beta-1000px](https://user-images.githubusercontent.com/5411013/120891607-ca8a5200-c609-11eb-99d8-02dd8d0a2295.png)

**Comment by sushain97** [comment] 2021-06-06 02:35
Incidentally fixed in https://github.com/apertium/apertium-html-tools/commit/c530c04f424c81df9f2aeda06a2c88b4a070c1cc. I believe this was due to a regression in the esbuild bundler: https://github.com/evanw/esbuild/pull/1342.

**Closed by sushain97** 2021-06-06 02:35 UTC
Labels: bug
